/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "mkfsvcomtvnykopnvetp"
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1rZnN2Y29tdHZueWtvcG52ZXRwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTkxNjI1NzEsImV4cCI6MjA3NDczODU3MX0.KTb5D0gbBdGtWyYkja-jWBODNNNNHUAq5gu-mMQgA6Y"